version: '3.5'
services:
  nswiki:
    build:
      context: .
      dockerfile: nswiki.dockerfile
      args:
        - EXP_PORT=8000
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./minicms:/app/minicms
    environment:
      MYSQL_HOST: "172.29.152.233"
      MYSQL_PORT: "3306"
      MYSQL_DB: "djangodb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "13723926068"
      LISTEN_ADDR: "0.0.0.0"