version: '3'
services:
  mysql:
    image:
      mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "13723926068"
      MYSQL_DATABASE: "djangodb"
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
  nswiki:
    build:
      context: .
      dockerfile: nswiki.dockerfile
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8000:8000"

volumes:
  mysql_db:
