version: '3.5'
services:
  mysql:
    image:
      mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "CHANGE_THIS_WITH_YOUR_PASSWD"
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql
  nswiki:
    build:
      context: .
      dockerfile: nswiki.dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./minicms:/app/minicms
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_PORT: "3306"
      MYSQL_DB: "djangodb"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "CHANGE_THIS_WITH_YOUR_PASSWD"
      LISTEN_ADDR: "0.0.0.0"
      LISTEN_PORT: "8000"

volumes:
  mysql_db:
